{{ config(materialized='external', location=var('output_path') + '/' + this.name + '.parquet') }}

SELECT
    "BOROUGH"::ENUM ('BRONX','BROOKLYN','MANHATTAN','QUEENS','STATEN I;iay;iaSLAND','STATEN ISLAND') AS "BOROUGH",
    regexp_replace("Job doc. #", '0', '')::ENUM ('1','2','3','4','5','6','7','8','9','10','11','12') AS "Job doc. #",
    "Job Type"::ENUM ('A1','A2','A3','DM','NB','SG') AS "Job Type",
    "Self_Cert"::ENUM ('J','N','R','X','Y') AS "Self_Cert",
    regexp_replace("Bldg Type", '0', '')::ENUM ('1','2') AS "Bldg Type",
    "Residential"::ENUM ('YES') AS "Residential",
    "Special District 2"::ENUM ('BPRK','GCP2','GW','HILI','IBZ','JAM','POPS') AS "Special District 2",
    "Work Type"::ENUM ('BL','CC','EQ','FA','FB','FP','FS','MH','NB','OT','PL','SD','SP') AS "Work Type",
    "Permit Status"::ENUM ('IN PROCESS','ISSUED','RE-ISSUED','REVOKED') AS "Permit Status",
    "Filing Status"::ENUM ('INITIAL','RENEWAL') AS "Filing Status",
    "Permit Type"::ENUM ('AL','DM','EQ','EW','FO','NB','PL','SG') AS "Permit Type",
    regexp_replace("Permit Sequence #", '0', '')::ENUM ('1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31','32','33','34','35','36') AS "Permit Sequence #",
    "Permit Subtype"::ENUM ('BL','CH','EA','FA','FB','FN','FP','FS','MH','OT','SC','SD','SF','SH','SP') AS "Permit Subtype",
    "Oil Gas"::ENUM ('GAS','OIL') AS "Oil Gas",
    "Site Fill"::ENUM ('NONE','NOT APPLICABLE','OFF-SITE','ON-SITE','USE UNDER 300 CU.YD') AS "Site Fill",
    "Permittee's License Type"::ENUM ('5S','DM','FS','GC','HI','MP','N','NW','OB','OW','PE','RA','SI','T@') AS "Permittees License Type",
    "Act as Superintendent"::ENUM ('A','N','Y') AS "Act as Superintendent",
    regexp_replace("Owner's Business Type", '[^a-zA-Z0-9-/;: ]', '', 'g')::ENUM ('2022-05-09 00:00:00','CONDO/CO-OP','CORPORATION','DCAS','DOE','HHC','HPD','INDIVIDUAL','NY STATE','NYC AGENCY','NYCHA','NYCHA/HHC','OTHER','OTHER GOVT AGENCY','PARTNERSHIP') AS "Owners Business Type",
    "Non-Profit"::ENUM ('8','N','Y','') AS "Non-Profit",
    "Owner’s House State"::ENUM ('AK','AZ','CA','CO','CT','DC','DE','FL','GA','IA','IL','IN','KS','KY','LA','MA','MD','ME','MI','MN','MO','NC','ND','NE','NH','NJ','NM','NV','NY','OH','OK','OR','PA','PR','RI','SC','SD','TN','TX','UT','VA','VT','WA') AS "Owners House State",
    regexp_replace("COUNCIL_DISTRICT", '0', '')::ENUM ('1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31','32','33','34','35','36','37','38','39','40','41','42','43','44','45','46','47','48','49','50','51') AS "COUNCIL_DISTRICT",
FROM read_csv('~/Downloads/DOB_Permit_Issuance_20240419.csv', 
            types={
                'Bldg Type': 'VARCHAR',
                'Residential': 'VARCHAR',
                'Permit Sequence #': 'VARCHAR',
                'COUNCIL_DISTRICT': 'VARCHAR',
                'Job Start Date': 'DATE', 
                'Filing Date': 'DATE', 
                'Issuance Date': 'DATE',
                'Expiration Date': 'DATE',
                },
            dateformat='%m/%d/%Y',
            ignore_errors=true)
